server:
  port: 8081
spring:
  application:
    name: esb-service
jwt:
  secret: "utd1234"

CLIENTES_API_URL: http://localhost:7000
USERS_API_URL: http://localhost:5000
EMAIL_API_URL: http://localhost:8000